import type { Metadata } from 'next';
import './globals.css';
import { ClerkProvider } from '@clerk/nextjs';
import { julius, roboto } from '@/lib/fonts';

export const metadata: Metadata = {
  title: {
    template: '%s | Life Etc',
    default: 'Life Etc',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${roboto.variable} ${julius.variable} antialiased`}>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
